Rename CLI to 'hippo'
deislabs/hippofactory pull request #41
Opened 2021-07-20 19:07 UTC by technosophos

Per the conversation in #31 and on chat, this renames the project to "The Hippo Client" and the CLI to `hippo`.

One notable thing I did not change b/c I am not sure if there are any external dependencies on this naming convention:

```
src/bindle_writer.rs
64:        if parcel.has_annotation("hippofactory_do_not_stage") {

src/expander.rs
505:    annotations.insert("hippofactory_do_not_stage".to_owned(), "true".to_owned());
```

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

2021-07-20 19:41 UTC, bacongobbler approved these changes
We'll have to make sure that the release workflow is updated to the new name once the repository is renamed. But I'm +1 on the move.

I'll let @itowlson weigh in here and see what he thinks about how we should handle the parcel annotations. We are pre-1.0 so it is fine to make breaking changes, but I wouldn't want to break any existing clients if they relied on this annotation... But I'm pretty sure it's just hippofactory/HIPPOFACTS logic.

2021-07-20 20:54 UTC, itowlson commented
The `do_not_stage` annotation is purely internal - nothing outside HF depends on it or should ever depend on it.  Ideally we would not even be storing it as an annotation, just a piece of transient data attached to the Parcel.  But I couldn't see a way to do that without creating _yet more_ Bindle-like-but-not-quite-Bindle data types which would be boring.

2021-07-20 22:05 UTC, itowlson requested changes
When comes a time to change a program's name
And ecosystem role to broaden wide
One scarce can keep the interface the same
Or else some harsh reviewer may deride

Now to this Hippo client turn our eyes
And principle that all here do embrace
To unify by many subcommands
It irks me deep that this be not the case

To `hippo push` or `hippo build` perchance
But `hippo` plain grants not the flex we need
And, more, this starts a dreadful naming dance
If Hippo's self its name we deem must yield

For server, client's names must not confect
And so, my liege, these changes must reject.

2021-07-20 22:24 UTC, technosophos commented
I have never been so happy about a rejection message.

2021-07-20 22:25 UTC, technosophos commented
Also, just to be clear... are you asking for _only_ `push`, or all of the subcommands from #31?

2021-07-20 22:31 UTC, itowlson commented
Apparently the sonnet form lacks crisp technical clarity and I should have written a villanelle instead.

I think there are two things we need to do:

1. Figure out what we want to call Hippo itself e.g. `hippo-server` (and arguably make that change first so we can keep repo names in sync)
2. Agree the subcommand that we want to move the existing functionality under, and implement that subcommand (so we know how this stuff is going to fit together)

We should definitely NOT try to shovel all the subcommands into this PR: I don't think there's a poetic form that could adequately express my feelings about that.

2021-07-20 22:41 UTC, bacongobbler commented
I like `hippo-server` if only for the reason that it is consistent with bindle's naming convention (`bindle`/`bindle-server`). I'll file the ticket and get cracking on that tomorrow unless someone beats me to the punch in the meantime.

2021-07-21 15:54 UTC, bacongobbler commented
So, how I'm thinking this will go down with deislabs/hippo#162 is that we rename the project "deislabs/hippo-cli". deislabs/hippo will still keep its current name, but the output binary changes its name to "hippo-server". When hippo-cli is compiled, the output is a binary named "hippo".

The reason I chose "deislabs/hippo" to be hippo-the-server and "deialsbs/hippo-cli" as hippo-the-cli because there may be many hippo client implementations to accommodate different client solutions (typescript libraries, TUIs, CLIs), but there will only be one implementation of the hippo server at any given point. I'm also running under the assumption that when users search for hippo, they'll more likely be searching for hippo-the-server than hippo-the-client.

Let me know if those assumptions seems wrong.

2021-07-21 16:47 UTC, technosophos commented
Okay, so my quick rename PR has morphed a bit. I am currently implementing:

- `hippo push` (formerly `-a all`)
- `hippo prepare` (formerly `-a prepare`)
- A to-be-named command (probably `hippo bindle`), formerly `-a bindle`.

The hard part is re-constructing which args apply to which verbs. Right now, I am sending all of the subcommands to `run()`, but we might at some point want to refactor that.

2021-07-21 20:34 UTC, technosophos commented
Also, yes, I agree that the repo should become `deislabs/hippo-cli`

2021-07-27 16:11 UTC, bacongobbler commented
From conversations with @technosophos yesterday, he may not be able to finish this up in time. I'm going to see if I can pick up where he left off today so we can carry forward with this work, as some of the documentation work necessary for Hippo v0.1.0 relies on this work.

2021-07-27 17:41 UTC, technosophos commented
Ready for re-review. The `hippo push` command could use some manually testing by someone who understands that workflow better than I. But I manually tested `hippo prepare` and `hippo bindle`, and as far as I can tell, they work the same as they did prior to the refactor.

2021-07-27 19:01 UTC, bacongobbler commented
Hmm... I can't tell if it's due to a change in this PR or if there's some other issue here. `hippo bindle .` works fine, but `hippo push .` does not.

```
><> hippo bindle .
pushed: helloworld/0.1.0-bacongobbler-2021.07.27.12.00.39.359
><> hippo push .
Error: Invalid request (status code 404): Some("")
```

I think it's because I asked `yo wasm` to not create a new application on hippo for me. Trying to see how to hook it up to the "helloworld" app.

2021-07-27 19:03 UTC, bacongobbler approved these changes
Aha! It was because my HIPPOFACTS file had `helloworld` as the name rather than `bacongobbler/helloworld`. After changing that everything works great.

```
><> hippo push .
pushed: bacongobbler/helloworld/0.1.0-bacongobbler-2021.07.27.12.02.52.065
```

LGTM!

2021-07-27 19:05 UTC, bacongobbler commented
Can confirm `hippo prepare` works the same as well.

2021-07-27 19:40 UTC, bacongobbler commented
I'm going ahead and merging this one in so we can move forward with the docs and repo rename. YOLO!

2021-07-27 19:40 UTC, merged